config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: "Admin::User"
  root to: 'groups#index'

  namespace :catalogs do
    resources :levels
    get 'levels/delete/:id' => 'levels#delete', as: 'level_delete'
  end

  resources :member_links
  resources :member_publications
  resources :group_members
  get 'group_members/delete/:id' => 'group_members#delete', as: 'group_member_delete'
  get 'group_members/fields_setup/:id' => 'group_members#fields_setup', as: 'fields_setup'
  get 'group_members/switch_status/:id' => 'group_members#switch_status', as: 'group_member_switch_status'
  get 'group_members/add_link/:id', to: 'group_members#add_link', as: 'group_member_add_link'
  get 'group_members/destroy_link/:id', to: 'group_members#destroy_link', as: 'group_member_destroy_link'
  get 'group_members/add_publication/:id', to: 'group_members#add_publication', as: 'group_member_add_publication'
  get 'group_members/destroy_publicacion/:id', to: 'group_members#destroy_publication', as: 'group_member_destroy_publication'
  get 'group_members/by_group/:group_id' => 'group_members#by_group', as: 'by_group'
  resources :links
  resources :publications
  resources :groups
  get 'groups/delete/:id' => 'groups#delete', as: 'group_delete'
  get 'groups/by_department/:department_id' => 'groups#by_department', as: 'by_department'
  namespace :catalogs do
    resources :pub_types
    get 'pub_types/delete/:id' => 'pub_types#delete', as: 'pub_type_delete'
  end
  namespace :catalogs do
    resources :statuses
  end
  namespace :catalogs do
    resources :member_types
    get 'member_types/delete/:id' => 'member_types#delete', as: 'member_type_delete'
  end
  namespace :catalogs do
    resources :locations
    get 'locations/delete/:id' => 'locations#delete', as: 'location_delete'
  end
  namespace :catalogs do
    resources :departments
    get 'departments/delete/:id' => 'departments#delete', as: 'department_delete'
  end
  namespace :admin do
    resources :users
    get 'not_authorized' => 'users#not_authorized', as: 'user_not_authorized'
    get 'users/delete/:id' => 'users#delete', as: 'user_delete'
    get 'users/groups_admin/:id' => 'users#edit_groups_admin', as: 'edit_groups_admin'
    post 'users/groups_admin/:id' => 'users#update_groups_admin', as: 'update_groups_admin'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member_link.rb
class MemberLink < ApplicationRecord
  belongs_to :group_member
  belongs_to :link
end

app/controllers/member_links_controller.rb
class MemberLinksController < ApplicationController
  before_action :set_member_link, only: [:show, :edit, :update, :destroy]

  # GET /member_links
  # GET /member_links.json
  def index
    @member_links = MemberLink.all
  end

  # GET /member_links/1
  # GET /member_links/1.json
  def show
  end

  # GET /member_links/new
  def new
    @member_link = MemberLink.new
  end

  # GET /member_links/1/edit
  def edit
  end

  # POST /member_links
  # POST /member_links.json
  def create
    @member_link = MemberLink.new(member_link_params)

    respond_to do |format|
      if @member_link.save
        format.html { redirect_to @member_link, notice: 'Member link was successfully created.' }
        format.json { render :show, status: :created, location: @member_link }
      else
        format.html { render :new }
        format.json { render json: @member_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_links/1
  # PATCH/PUT /member_links/1.json
  def update
    respond_to do |format|
      if @member_link.update(member_link_params)
        format.html { redirect_to @member_link, notice: 'Member link was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_link }
      else
        format.html { render :edit }
        format.json { render json: @member_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_links/1
  # DELETE /member_links/1.json
  def destroy
    @member_link.destroy
    respond_to do |format|
      format.html { redirect_to member_links_url, notice: 'Member link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_link
      @member_link = MemberLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_link_params
      params.require(:member_link).permit(:group_member_id, :link_id)
    end
end

app/helpers/member_links_helper.rb
module MemberLinksHelper
end

app/views/member_links/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@member_link) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :group_member
    = f.association :link

  .form-actions
    = f.button :submit

app/views/member_links/edit.html.haml
%h1 Editing member_link

= render 'form'

= link_to 'Show', @member_link
\|
= link_to 'Back', member_links_path

app/views/member_links/index.html.haml
%h1 Listing member_links

%table
  %thead
    %tr
      %th Group member
      %th Link
      %th
      %th
      %th

  %tbody
    - @member_links.each do |member_link|
      %tr
        %td= member_link.group_member
        %td= member_link.link
        %td= link_to 'Show', member_link
        %td= link_to 'Edit', edit_member_link_path(member_link)
        %td= link_to 'Destroy', member_link, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Member link', new_member_link_path

app/views/member_links/new.html.haml
%h1 New member_link

= render 'form'

= link_to 'Back', member_links_path

app/views/member_links/show.html.haml
%p#notice= notice

%p
  %b Group member:
  = @member_link.group_member
%p
  %b Link:
  = @member_link.link

= link_to 'Edit', edit_member_link_path(@member_link)
\|
= link_to 'Back', member_links_path