config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: "Admin::User"
  root to: 'groups#index'

  namespace :catalogs do
    resources :levels
    get 'levels/delete/:id' => 'levels#delete', as: 'level_delete'
  end

  resources :member_links
  resources :member_publications
  resources :group_members
  get 'group_members/delete/:id' => 'group_members#delete', as: 'group_member_delete'
  get 'group_members/fields_setup/:id' => 'group_members#fields_setup', as: 'fields_setup'
  get 'group_members/switch_status/:id' => 'group_members#switch_status', as: 'group_member_switch_status'
  get 'group_members/add_link/:id', to: 'group_members#add_link', as: 'group_member_add_link'
  get 'group_members/destroy_link/:id', to: 'group_members#destroy_link', as: 'group_member_destroy_link'
  get 'group_members/add_publication/:id', to: 'group_members#add_publication', as: 'group_member_add_publication'
  get 'group_members/destroy_publicacion/:id', to: 'group_members#destroy_publication', as: 'group_member_destroy_publication'
  get 'group_members/by_group/:group_id' => 'group_members#by_group', as: 'by_group'
  resources :links
  resources :publications
  resources :groups
  get 'groups/delete/:id' => 'groups#delete', as: 'group_delete'
  get 'groups/by_department/:department_id' => 'groups#by_department', as: 'by_department'
  namespace :catalogs do
    resources :pub_types
    get 'pub_types/delete/:id' => 'pub_types#delete', as: 'pub_type_delete'
  end
  namespace :catalogs do
    resources :statuses
  end
  namespace :catalogs do
    resources :member_types
    get 'member_types/delete/:id' => 'member_types#delete', as: 'member_type_delete'
  end
  namespace :catalogs do
    resources :locations
    get 'locations/delete/:id' => 'locations#delete', as: 'location_delete'
  end
  namespace :catalogs do
    resources :departments
    get 'departments/delete/:id' => 'departments#delete', as: 'department_delete'
  end
  namespace :admin do
    resources :users
    get 'not_authorized' => 'users#not_authorized', as: 'user_not_authorized'
    get 'users/delete/:id' => 'users#delete', as: 'user_delete'
    get 'users/groups_admin/:id' => 'users#edit_groups_admin', as: 'edit_groups_admin'
    post 'users/groups_admin/:id' => 'users#update_groups_admin', as: 'update_groups_admin'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :catalogs_pub_type, :class_name => 'Catalogs::PubType'
  validates :title, :pub_date, presence: true
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :link, :catalogs_pub_type_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@publication) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :link
    = f.association :catalogs_pub_type, label_method: :name_es

  .form-actions
    = f.button :submit

app/views/publications/edit.html.haml
%h1 Editing publication

= render 'form'

= link_to 'Show', @publication
\|
= link_to 'Back', publications_path

app/views/publications/index.html.haml
%h1 Listing publications

%table
  %thead
    %tr
      %th Title
      %th Link
      %th Catalogs pub type
      %th
      %th
      %th

  %tbody
    - @publications.each do |publication|
      %tr
        %td= publication.title
        %td= publication.link
        %td= publication.catalogs_pub_type
        %td= link_to 'Show', publication
        %td= link_to 'Edit', edit_publication_path(publication)
        %td= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Publication', new_publication_path

app/views/publications/new.html.haml
%h1 New publication

= render 'form'

= link_to 'Back', publications_path

app/views/publications/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @publication.title
%p
  %b Link:
  = @publication.link
%p
  %b Catalogs pub type:
  = @publication.catalogs_pub_type

= link_to 'Edit', edit_publication_path(@publication)
\|
= link_to 'Back', publications_path