config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: "Admin::User"
  root to: 'groups#index'

  namespace :catalogs do
    resources :levels
    get 'levels/delete/:id' => 'levels#delete', as: 'level_delete'
  end

  resources :member_links
  resources :member_publications
  resources :group_members
  get 'group_members/delete/:id' => 'group_members#delete', as: 'group_member_delete'
  get 'group_members/fields_setup/:id' => 'group_members#fields_setup', as: 'fields_setup'
  get 'group_members/switch_status/:id' => 'group_members#switch_status', as: 'group_member_switch_status'
  get 'group_members/add_link/:id', to: 'group_members#add_link', as: 'group_member_add_link'
  get 'group_members/destroy_link/:id', to: 'group_members#destroy_link', as: 'group_member_destroy_link'
  get 'group_members/add_publication/:id', to: 'group_members#add_publication', as: 'group_member_add_publication'
  get 'group_members/destroy_publicacion/:id', to: 'group_members#destroy_publication', as: 'group_member_destroy_publication'
  get 'group_members/by_group/:group_id' => 'group_members#by_group', as: 'by_group'
  resources :links
  resources :publications
  resources :groups
  get 'groups/delete/:id' => 'groups#delete', as: 'group_delete'
  get 'groups/by_department/:department_id' => 'groups#by_department', as: 'by_department'
  namespace :catalogs do
    resources :pub_types
    get 'pub_types/delete/:id' => 'pub_types#delete', as: 'pub_type_delete'
  end
  namespace :catalogs do
    resources :statuses
  end
  namespace :catalogs do
    resources :member_types
    get 'member_types/delete/:id' => 'member_types#delete', as: 'member_type_delete'
  end
  namespace :catalogs do
    resources :locations
    get 'locations/delete/:id' => 'locations#delete', as: 'location_delete'
  end
  namespace :catalogs do
    resources :departments
    get 'departments/delete/:id' => 'departments#delete', as: 'department_delete'
  end
  namespace :admin do
    resources :users
    get 'not_authorized' => 'users#not_authorized', as: 'user_not_authorized'
    get 'users/delete/:id' => 'users#delete', as: 'user_delete'
    get 'users/groups_admin/:id' => 'users#edit_groups_admin', as: 'edit_groups_admin'
    post 'users/groups_admin/:id' => 'users#update_groups_admin', as: 'update_groups_admin'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  has_one_attached :avatar
  has_one_attached :research_photo
  has_one_attached :resume

  belongs_to :group
  belongs_to :catalogs_member_type, class_name: 'Catalogs::MemberType'
  belongs_to :catalogs_status, class_name: 'Catalogs::Status'
  belongs_to :catalogs_level, :class_name => 'Catalogs::Level'

  has_many :member_links
  has_many :links, through: :member_links, dependent: :destroy
  accepts_nested_attributes_for :links, allow_destroy: true, reject_if: :all_blank

  has_many :member_publications
  has_many :publications, through: :member_publications, dependent: :destroy
  accepts_nested_attributes_for :publications, allow_destroy: true, reject_if: :all_blank

  #todo validate text fields (length)
  #todo remove unnecessary fields

  validates :firstname, :lastname, presence: true

  scope :from_group, -> (group_id) {where("group_id = ?", group_id) }

  def self.search(search)
    if search
      where("translate(lower(lastname),'áéíóúàèìòù', 'aeiouaeiou') LIKE translate(lower(?),'áéíóúàèìòù', 'aeiouaeiou')"\
            " OR translate(lower(firstname),'áéíóúàèìòù', 'aeiouaeiou') LIKE translate(lower(?),'áéíóúàèìòù', 'aeiouaeiou')",
            "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  def name
    "#{lastname} #{firstname}"
  end
end

app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController
  require 'yaml'

  before_action :set_group_member, only: [:show, :edit, :update, :destroy, :delete, :switch_status]
  helper_method :sort_column, :sort_direction

  # GET /group_members
  # GET /group_members.json
  def index
    @resources = GroupMember.search(params[:search]).where(group_id: current_user.admin_groups).order("#{sort_column} #{sort_direction}").paginate(per_page: 11, page:  params[:page])
  end

  def by_group
    @resources = GroupMember.from_group(params[:group_id]).where(group_id: current_user.admin_groups).search(params[:search]).order("#{sort_column} #{sort_direction}").paginate(per_page: 11, page:  params[:page])
  end

  # GET /group_members/1
  # GET /group_members/1.json
  def show
  end

  # GET /group_members/new
  def new
    @resource = GroupMember.new
    #2.times do
    #  @resource.links.build
    #end
  end

  # GET /group_members/1/edit
  def edit
  end

  # POST /group_members
  # POST /group_members.json
  def create
    @resource = GroupMember.new(group_member_params)
    authorize @resource
    respond_to do |format|
      if @resource.save
        attach_active_resources
        format.html { redirect_to group_member_path(id: @resource, group_id: params[:group_id]), notice: 'Group member was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_members/1
  # PATCH/PUT /group_members/1.json
  def update
    respond_to do |format|
      if @resource.update(group_member_params)
        @resource.avatar.purge if params[:group_member][:remove_avatar] == '1'
        @resource.research_photo.purge if params[:group_member][:remove_research_photo] == '1'
        format.html { redirect_to group_member_path(id: @resource, group_id: params[:group_id]), notice: t('notices.updated_successfully')}
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @group_id = params[:group_id]
  end

  # DELETE /group_members/1
  # DELETE /group_members/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      if params[:group_id]
        format.html { redirect_to by_group_path(params[:group_id]), flash: {warning: t('notices.destroyed') }}
      else
        format.html { redirect_to group_members_url, flash: {warning: t('notices.destroyed') }}
      end
      format.json { head :no_content }
    end
  end

  def fields_setup
    member_type = Catalogs::MemberType.find(params[:id])
    gm_attrs = member_type.get_full_custom_attrs + member_type.get_default_attrs
    @gm_attrs = gm_attrs.map!{|attr| "group_member_#{attr}"}
    puts @gm_attrs
  end

  def switch_status
    respond_to do |format|
      if @resource.catalogs_status_id == 1
        @resource.update!(catalogs_status_id: 2)
        flash[:warning] = t('notices.member_inactivated')
      else
        @resource.update!(catalogs_status_id: 1)
        flash[:alert] = t('notices.member_activated')
      end
      format.html { redirect_to group_members_url }
    end
  end

  def attach_active_resources
    @resource.avatar.attach(params[:avatar])
    @resource.avatar.attach(params[:research_photo])
  end

  def add_link
  end

  def destroy_link
    @link_id = params[:id]
  end

  def add_publication
  end

  def destroy_publication
    @publication_id = params[:id]
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group_member
    @resource = GroupMember.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_member_params
    params.require(:group_member).permit(:group_id, :firstname, :lastname, :photo_file_name, :email,
                                         :phone_numbers, :academic_career_es, :academic_career_en, :activities_or_topics_es, :activities_or_topics_en,
                                         :research_interests_es, :research_interests_en, :photo_res_file_name,
                                         :research_photo_descr_es, :research_photo_descr_en, :catalogs_member_type_id,
                                         :catalogs_status_id, :current_position_es, :current_position_en,
                                         :current_workplace, :avatar, :research_photo, :resume, :catalogs_level_id,
                                         links_attributes: [:id, :name_es, :name_en, :link, :_destroy],
                                         publications_attributes: [:id, :catalogs_pub_type_id, :title, :link, :pub_date, :_destroy])
  end

  def sort_column
    params[:sort] || 'lastname'
  end

  def sort_direction
    params[:direction] || 'asc'
  end
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/views/group_members/_form.html.haml
-# frozen_string_literal: true
= simple_form_for @resource, remote: false do |f|

  - link_to_close = link_to "<span class='fas fa-times'></span> #{t('commands.close')}".html_safe,
    params[:group_id].nil? ? group_members_path : by_group_path(params[:group_id]), class: "button btn btn-secondary"
  - link_to_save = f.button :submit, t('commands.save'), class: "btn-primary"

  - unless params[:group_id].nil?
    = hidden_field_tag :group_id, params[:group_id]

  .text-right
    = link_to_close.html_safe
    = link_to_save.html_safe
  %hr

  = f.error_notification
  .row
    .col-2= f.label t('activerecord.attributes.group_member.group_and_member_type')
    - if params[:group_id]
      .col-5= f.association :group, label_method: :name_es, prompt: t('messages.choose_group'), label: false, selected: params[:group_id], disabled: true
    -else
      .col-5= f.association :group, collection: current_user.admin_groups_collection, label_method: :name_es, prompt: t('messages.choose_group'), label: false

    .col-5= f.association :catalogs_member_type, collection: Catalogs::MemberType.order('rank'), label_method: :name_es, prompt: t('messages.choose_member_type'), label: false
  .row
    .col-2= f.label :firstname
    .col-3= f.input :firstname, label: false
    .col-2.text-right= f.label :lastname
    .col-5= f.input :lastname, label: false
  .row
    .col-2= f.label :email
    .col-3= f.input :email, label: false, as: :email
    .col-2.text-right= f.label :phone_numbers
    .col-5= f.input :phone_numbers, label: false, hint: 'Incluir clave lada del México y el número a 10 dígitos: (52) 442 XXXXXXX'

  .row
    .col-2
      = f.label :avatar
    .col-3
      = f.file_field :avatar, accept: 'image/png,image/gif,image/jpeg,image/psd', id:'avatar-file-upload'
    .col-7.text-truncate
      -if @resource.avatar.attached?
        = f.input 'remove_avatar', :as => :boolean, label: t('activerecord.attributes.group_member.remove_attach', filename: @resource.avatar.filename), wrapper_html: { class: 'sf-checkbox pl-5' }, input_html: { :checked => "unchecked"}

  %br
  .row.group_member_level
    .col-2= f.label :level
    .col-5= f.association :catalogs_level, label_method: :name_es, label: false

  %hr


  .group_member_links.links.p-2
    .row
      .col-2
        = link_to_add_row t('commands.add_link'), group_member_add_link_path(@resource.links.count), f, :links, class: 'btn mr-sm-2 btn-secondary', remote: true, id: 'add_link_button'
      .col-10.mt-3
        Links relevantes : página del grupo, ORCID, ResearchGate, PubFacts, Tweeter académico, blog académico, etc.
    #link_list
      = f.simple_fields_for :links do |builder|
        = render 'link', b: builder

  %hr

  .group_member_publications.publications.p-2
    .row
      .col-3
        = link_to_add_row t('commands.add_publication'), group_member_add_publication_path(@resource.publications.count), f, :publications, class: 'btn mr-sm-2 btn-secondary', remote: true, id: 'add_publication_button'
      .col-9.mt-3
        Artículos y revisiones, capítulos de libros, otras. Formato recomendado
        %strong PubMed Sumary (text).
        Máximo 10. Ejemplo:
    .row.no-gutters
      .col-12.mt-3.border.rounded.p-2
        Ishida M, Ushioda S, Nagasawa Y, Komuroa Y, Tang Z, Hu L, Tamura T, Sakatani K.
        Development of an IoT-Based Monitorin System for Healthcare: A Preliminary Study. Adv Exp Med Biol. 2020;1232:291-297.
        doi: 10.1007/978-3-030-34461-0_37. PubMed PMID: 31893423.
    #publication_list
      = f.simple_fields_for :publications do |builder|
        = render 'publication', b: builder

  %hr

  .row.group_member_resume
    .col-3
      = f.label :resume
    .col-3.mb-2
      = f.file_field :resume, accept: 'application/pdf', id:'resume-upload'
    .col-6.text-truncate
      -if @resource.resume.attached?
        = f.input 'remove_resume', :as => :boolean, label: t('activerecord.attributes.group_member.remove_attach', filename: @resource.resume.filename), wrapper_html: { class: 'sf-checkbox pl-5' }, input_html: { :checked => "unchecked"}
  = f.input :activities_or_topics_es, :input_html => {:rows => 5, maxlength: 300}, placeholder: t('messages.max_chars', chars: 300)
  = f.input :activities_or_topics_en, :input_html => {:rows => 5, maxlength: 300}, placeholder: t('messages.max_chars', chars: 300)
  = f.input :academic_career_es, :input_html => {:rows => 5, maxlength: 500}, placeholder: t('messages.max_chars', chars: 500)
  = f.input :academic_career_en, :input_html => {:rows => 5, maxlength: 500}, placeholder: t('messages.max_chars', chars: 500)
  = f.input :research_interests_es, :input_html => {:rows => 10, maxlength: 2000}, placeholder: t('messages.max_chars', chars: 2000)
  = f.input :research_interests_en, :input_html => {:rows => 10, maxlength: 2000}, placeholder: t('messages.max_chars', chars: 2000)

  .row.group_member_research_photo
    .col-2
      = f.label :research_photo
    .col-3.mb-2
      = f.file_field :research_photo, accept: 'image/png,image/gif,image/jpeg,image/psd', id:'research-photo-upload'
    .col-7.text-truncate
      -if @resource.research_photo.attached?
        = f.input 'remove_research_photo', :as => :boolean, label: t('activerecord.attributes.group_member.remove_attach', filename: @resource.research_photo.filename), wrapper_html: { class: 'sf-checkbox pl-5' }, input_html: { :checked => "unchecked"}

  = f.input :research_photo_descr_es, :input_html => { maxlength: 180}, placeholder: t('messages.max_chars', chars: 180)
  = f.input :research_photo_descr_en, :input_html => { maxlength: 180}, placeholder: t('messages.max_chars', chars: 180)

  %br
  %h6
    Llenar la siguiente sección
    %strong sólo para ex-miebros
    del grupo de trabajo:
  %hr

  .row
    .col-2= f.label t('activerecord.attributes.group_member.current_workplace')
    .col-10= f.input :current_workplace, label: false
  .row
    .col-2= f.label t('activerecord.attributes.group_member.current_position_es')
    .col-10= f.input :current_position_es, label: false
  .row
    .col-2= f.label t('activerecord.attributes.group_member.current_position_en')
    .col-10= f.input :current_position_en, label: false

  %hr
  .text-right
    = link_to_close.html_safe
    = link_to_save.html_safe

app/views/group_members/_link.html.haml
.row.m-3{id: "link_record_#{local_assigns[:b].index}"}
  .col-4
    = b.input :link, hint: 'URL del enlace, ej. https://orcid.org/0000-0000-0000-000X'
  .col-3
    = b.input :name_es, hint: 'Nombre para mostrar, ej. ORCID'
  .col-3
    = b.input :name_en, hint: 'Nombre para mostrar (inglés), ej. ORCID'
  .col-2.text-center
    = b.input_field :_destroy, as: :hidden
    .mt-4= link_to_fa_button({url: group_member_destroy_link_path(local_assigns[:b].index), remote: true, icon: 'fa-unlink', title: t('commands.remove_link'), html_class: 'btn-light'})

app/views/group_members/_new_link.html.haml
#TODO Delete this file
.row.m-3.link_record
  .col-4
    .form-group.string.required.group_member_links_link
      =label_tag :link
      %abbr{:title => "required"} *
      %input#group_member_links_attributes_0_link.form-control.string.required{:name => "group_member[links_attributes][0][link]", :placeholder => "www.personal.org", :type => "text", :value => ""}/
      %small.form-text.text-muted URL del enlace
  .col-3
    .form-group.string.required.group_member_links_name_es
      %label.string.required{:for => "group_member_links_attributes_0_name_es"}
        Nombre
        %abbr{:title => "required"} *
      %input#group_member_links_attributes_0_name_es.form-control.string.required{:name => "group_member[links_attributes][0][name_es]", :placeholder => "Página personal", :type => "text", :value => ""}/
      %small.form-text.text-muted Nombre para mostrar
  .col-3
    .form-group.string.required.group_member_links_name_en
      %label.string.required{:for => "group_member_links_attributes_0_name_en"}
        Nombre (ingés)
        %abbr{:title => "required"} *
      %input#group_member_links_attributes_0_name_en.form-control.string.required{:name => "group_member[links_attributes][0][name_en]", :placeholder => "Personal page", :type => "text", :value => ""}/
      %small.form-text.text-muted Nombre para mostrar (inglés)
  .col-2.text-center
    .mt-4
      %a.btn.btn-light{"data-remote" => "true", :href => "/", :title => "Eliminar link"}
        %span.fa.fa-unlink
%input#group_member_links_attributes_0_id{:name => "group_member[links_attributes][0][id]", :type => "hidden", :value => "3"}/




-#= simple_form_for @new_link do |l|
  .row.m-3.link_record
    .col-4
      = l.input :link, placeholder: 'www.personal.org', hint: 'URL del enlace'
    .col-3
      = l.input :name_es, placeholder: 'Página personal', hint: 'Nombre para mostrar'
    .col-3
      = l.input :name_en, placeholder: 'Personal page', hint: 'Nombre para mostrar (inglés)'
    .col-2.text-center
      .mt-4= link_to_fa_button({url: '/', remote: true, icon: 'fa-unlink', title: t('commands.remove_link'), html_class: 'btn-light'})

-#= f.simple_fields_for :links do |l|
  .col-4
    = l.text_field :link, placeholder: 'www.personal.org', hint: 'URL del enlace'

app/views/group_members/_publication.html.haml
.pub.m-3{id: "publication_record_#{local_assigns[:b].index}"}
  .row
    .col-3
      = b.association :catalogs_pub_type, label_method: :name_es,  selected: '1'
    .col-3
      = b.input :pub_date, as: :date, order: [:month, :year]
    .col-5
      = b.input :link
    .col-1.text-center
      = b.input_field :_destroy, as: :hidden
      .mt-4= link_to_fa_button({url: group_member_destroy_publication_path(local_assigns[:b].index), remote: true, icon: 'fa-trash-alt', title: t('commands.remove_publication'), html_class: 'btn-light'})
  .row
    .col-11
      = b.input :title, :input_html => {:rows => 7}

app/views/group_members/_records.html.haml
- es = "activerecord.attributes.group_member"
= flash_messages(flash)

%table.table.table-striped.table-hover
  %thead
    %tr.row.ml-0.mr-0
      %th.col-3{:scope => "col"}= sortable 'firstname', t("#{es}.firstname"),  eval("#{hnp}_path")
      %th.col-2{:scope => "col"}= sortable 'lastname', t("#{es}.lastname"),  eval("#{hnp}_path")
      - if action_name == 'by_group'
        %th.col-3{:scope => "col"}= t("#{es}.catalogs_member_type")
      - else
        %th.col-3{:scope => "col"}= sortable 'group_id', t("#{es}.group"),  eval("#{hnp}_path")
      %th.col-4{:scope => "col"}
  %tbody
    - @resources.each do |resource|
      -#if can? :update, resource
      %tr.row.ml-0.mr-0
        %td.col-3.text-truncate= resource.firstname
        %td.col-2.text-truncate= resource.lastname
        - if action_name == 'by_group'
          %td.col-3.text-truncate= resource.catalogs_member_type.name_es
        - else
          %td.col-3.text-truncate= resource.group.name_es
        %td.col-4.text-center
          = link_to_fa_button({url: group_member_path(id: resource, group_id: params[:group_id]), icon: 'fa-eye', title: t('commands.show'),  html_class: 'btn-light', remote: false})
          = link_to_fa_button({url: edit_group_member_path(resource, group_id: params[:group_id]), icon: 'fa-pencil-alt', title: t('commands.edit'), html_class: 'btn-light', remote: false})
          = link_to_fa_button({url: group_member_delete_path(resource, group_id: params[:group_id]), icon: 'fa-trash-alt', title: t('commands.delete'), data: {toggle: 'modal', target: '#delete-dialog'}, html_class: 'btn-light'})
          -if resource.catalogs_status_id == 1
            = link_to_fa_button({url: group_member_switch_status_path(resource), remote: false, icon: 'fa-user-plus', title: t('commands.status_active'), html_class: 'btn-light'})
          -else
            = link_to_fa_button({url: group_member_switch_status_path(resource), remote: false, icon: 'fa-user-minus', title: t('commands.status_active'), html_class: 'btn-light'})

app/views/group_members/add_link.js.haml
var regexp, time;
time = new Date().getTime();
regexp = new RegExp($('a#add_link_button').data('id'), 'g');
$('#link_list').prepend($('a#add_link_button').data('fields').replace(regexp, time));

app/views/group_members/add_publication.js.haml
var regexp, time;
time = new Date().getTime();
regexp = new RegExp($('a#add_publication_button').data('id'), 'g');
$('#publication_list').prepend($('a#add_publication_button').data('fields').replace(regexp, time));

app/views/group_members/delete.js.haml
- @group_id ? (url =  group_member_path(id: @resource, group_id: @group_id)) : (url = @resource)
$('#delete-dialog').html("#{escape_javascript(render(partial: 'layouts/delete', locals: {title: @resource.name, record: url } ))}");

app/views/group_members/destroy_link.js.haml
$("#{"#group_member_links_attributes_#{@link_id}__destroy"}").val('true');
$("#{"#link_record_#{@link_id}"}").hide();

app/views/group_members/destroy_publication.js.haml
$("#{"#group_member_publication_attributes_#{@publication_id}__destroy"}").val('true');
$("#{"#publication_record_#{@publication_id}"}").hide();

app/views/group_members/edit.html.haml
%p.modal-header.text-center.alert.mt-2.mb-3.h5
  = t('group_member')
= render 'form'
%br

= javascript_pack_tag 'mt_setup_fields', 'data-turbolinks-track': 'reload'

-#
  %h1 Editing group_member

  = render 'form'

  = link_to 'Show', @group_member
  \|
  = link_to 'Back', group_members_path

app/views/group_members/fields_setup.js.haml
:plain
  $.each($("div[class*='group_member_']"), function(i, field){
    field_c = $.grep( $(field).attr('class').split(' '), function( n, i ) {return n.startsWith("group_member_");})[0];
    var gm_attrs = eval("#{escape_javascript(@gm_attrs.to_s).html_safe}")
    if($.inArray(field_c, gm_attrs) >= 0 ){
      $(field).show();
    } else {
      $(field).hide();
    }
  });

app/views/group_members/index.html.haml
// Table name singular, for url helpers
- helper_name_s = @resources.table_name.singularize
// Table name plural, for url helpers
- helper_name_p = @resources.table_name

- new_link = link_to_fa_button({url: eval("new_#{helper_name_s}_path"), text: t('commands.new'), html_class: 'btn-secondary', icon: 'fa-plus', remote: false})
= render partial: 'layouts/admin_menu', locals: {title: t(@resources.table_name), index_url: eval("#{helper_name_p}_path"), new_link: new_link}

%br

#records
  = render partial: 'records', locals: {hnp: helper_name_p, hns: helper_name_s}
#show-dialog.modal{:role => "dialog", :tabindex => "-1"}
#new-update-dialog.modal{:role => "dialog", :tabindex => "-1"}
#delete-dialog.modal{:role => "dialog", :tabindex => "-1"}

-#%p.text-center= will_paginate @resources
%nav{"aria-label" => "..."}
  #paginate.pagination.justify-content-center.pagination-sm
    = will_paginate @resources, :container => false
%br

= javascript_pack_tag 'paginate', 'data-turbolinks-track': 'reload'

app/views/group_members/new.html.haml
%p.modal-header.text-center.alert.mt-2.mb-3.h5
  = t('group_member')
= render 'form'
%br

= javascript_pack_tag 'mt_setup_fields', 'data-turbolinks-track': 'reload'