config/routes.rb
Rails.application.routes.draw do

  devise_for :users, class_name: "Admin::User"
  root to: 'groups#index'

  namespace :catalogs do
    resources :levels
    get 'levels/delete/:id' => 'levels#delete', as: 'level_delete'
  end

  resources :member_links
  resources :member_publications
  resources :group_members
  get 'group_members/delete/:id' => 'group_members#delete', as: 'group_member_delete'
  get 'group_members/fields_setup/:id' => 'group_members#fields_setup', as: 'fields_setup'
  get 'group_members/switch_status/:id' => 'group_members#switch_status', as: 'group_member_switch_status'
  get 'group_members/add_link/:id', to: 'group_members#add_link', as: 'group_member_add_link'
  get 'group_members/destroy_link/:id', to: 'group_members#destroy_link', as: 'group_member_destroy_link'
  get 'group_members/add_publication/:id', to: 'group_members#add_publication', as: 'group_member_add_publication'
  get 'group_members/destroy_publicacion/:id', to: 'group_members#destroy_publication', as: 'group_member_destroy_publication'
  get 'group_members/by_group/:group_id' => 'group_members#by_group', as: 'by_group'
  resources :links
  resources :publications
  resources :groups
  get 'groups/delete/:id' => 'groups#delete', as: 'group_delete'
  get 'groups/by_department/:department_id' => 'groups#by_department', as: 'by_department'
  namespace :catalogs do
    resources :pub_types
    get 'pub_types/delete/:id' => 'pub_types#delete', as: 'pub_type_delete'
  end
  namespace :catalogs do
    resources :statuses
  end
  namespace :catalogs do
    resources :member_types
    get 'member_types/delete/:id' => 'member_types#delete', as: 'member_type_delete'
  end
  namespace :catalogs do
    resources :locations
    get 'locations/delete/:id' => 'locations#delete', as: 'location_delete'
  end
  namespace :catalogs do
    resources :departments
    get 'departments/delete/:id' => 'departments#delete', as: 'department_delete'
  end
  namespace :admin do
    resources :users
    get 'not_authorized' => 'users#not_authorized', as: 'user_not_authorized'
    get 'users/delete/:id' => 'users#delete', as: 'user_delete'
    get 'users/groups_admin/:id' => 'users#edit_groups_admin', as: 'edit_groups_admin'
    post 'users/groups_admin/:id' => 'users#update_groups_admin', as: 'update_groups_admin'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name_en, :name_es, :catalogs_location_id, :catalogs_department_id, presence: true
  belongs_to :catalogs_department, :class_name => 'Catalogs::Department'
  belongs_to :catalogs_location, :class_name => 'Catalogs::Location'
  has_many :group_members, dependent: :destroy
  has_many :admin_user_groups, dependent: :destroy, :class_name => 'Admin::UserGroup'

  scope :from_department, -> (department_id) {where("catalogs_department_id = ?", department_id) }

  def self.search(search)
    if search
      where("translate(lower(name_es),'áéíóúàèìòù', 'aeiouaeiou') LIKE translate(lower(?),'áéíóúàèìòù', 'aeiouaeiou')", "%#{search}%")
    else
      all
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :delete]
  helper_method :sort_column, :sort_direction

  # GET /groups
  # GET /groups.json
  def index
    @resources = Group.search(params[:search]).where(id: current_user.admin_groups).order("#{sort_column} #{sort_direction}").paginate(per_page: 11, page:  params[:page])
    authorize @resources
  end

  def by_department
    @resources = Group.from_department(params[:department_id]).search(params[:search]).order("#{sort_column} #{sort_direction}").paginate(per_page: 11, page:  params[:page])
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    authorize @resource
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /groups/new
  def new
    @resource = Group.new
    authorize @resource
  end

  # GET /groups/1/edit
  def edit
    authorize @resource
  end

  # POST /groups
  # POST /groups.json
  def create
    @resource = Group.new(group_params)

    respond_to do |format|
      if @resource.save
        index

        flash[:success] = t('notices.saved_successfully')
        format.html { redirect_to @resource, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @resource.update(group_params)
        # Load records in order to refresh index page
        index
        flash[:success] = t('notices.updated_successfully')
        format.html { redirect_to @resource, warning: 'Group was successfully updated.'}
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def delete
    authorize @resource
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, flash: {warning: t('notices.destroyed') }}
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @resource = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name_es, :name_en, :catalogs_location_id, :catalogs_department_id)
  end

  def sort_column
    params[:sort] || 'name_es'
  end

  def sort_direction
    params[:direction] || 'asc'
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
-# frozen_string_literal: true

= simple_form_for @resource, remote: true, html: { class: 'form-horizontal' },  wrapper: :horizontal_form, wrapper_mappings: {check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|

  = f.error_notification

  = f.input :name_es
  = f.input :name_en
  - if(params[:department_id])
    = f.association :catalogs_department, label_method: :name_es, disabled: true, selected: params[:department_id]
  - else
    = f.association :catalogs_department, label_method: :name_es

  = f.association :catalogs_location, label_method: :name_es
  .modal-footer
    .text-right
      = button_tag "<span class='fas fa-times'></span> #{t('commands.close')}".html_safe, data: { dismiss: "modal", type: 'button'}, class: 'button btn btn-secondary'
      = f.button :submit, t('commands.save'), class: "btn-primary"

app/views/groups/_records.html.haml
- es = "activerecord.attributes.group"
= flash_messages(flash)

%table.table.table-striped.table-hover
  %thead
    %tr.row.ml-0.mr-0
      -if(params[:department_id])
        %th.col-9{:scope => "col"}= sortable 'name_es', t("#{es}.name_es"),  by_department_url(params[:department_id])
      - else
        %th.col-9{:scope => "col"}= sortable 'name_es', t("#{es}.name_es"),  eval("#{hnp}_path")
      %th.col-3{:scope => "col"}
  %tbody
    - @resources.each do |resource|
      -#if can? :update, resource
      %tr.row.ml-0.mr-0
        %td.col-9.text-truncate= resource.name_es
        %td.col-3.text-center
          = link_to_fa_button({url: by_department_url(resource), icon: 'fa-users', title: t('commands.show_members'), remote: false, html_class: 'btn-light'})
          = link_to_fa_button({url: resource, icon: 'fa-eye', title: t('commands.show'), data: {toggle: 'modal', target: '#show-dialog'}, html_class: 'btn-light'})
          = link_to_fa_button({url: eval("edit_#{hns}_path(resource)"), icon: 'fa-pencil-alt', title: t('commands.edit'), data: {toggle: 'modal', target: '#new-update-dialog'}, html_class: 'btn-light'})
          = link_to_fa_button({url: eval("#{hns}_delete_path(resource)"), icon: 'fa-trash-alt', title: t('commands.delete'), data: {toggle: 'modal', target: '#delete-dialog'}, html_class: 'btn-light'})

app/views/groups/_show.html.haml
- es = 'activerecord.attributes.group'
%table.table
  %tbody
    %tr
      %td.th
        = t("#{es}.name_es")
      %td.tc
        = @resource.name_es
    %tr
      %td.th
        = t("#{es}.name_en")
      %td.tc
        = @resource.name_en
    %tr
      %td.th
        = t("#{es}.location")
      %td.tc
        = @resource.catalogs_location.name_es

.modal-footer
  = button_tag "<span class='fas fa-times'></span> #{t('commands.close')}".html_safe, data: { dismiss: "modal", type: 'button'}, class: 'button btn btn-secondary'
  -#%button.btn{:type => "button"} #{t('commands.edit')}
  = link_to_fa_button({url: eval("edit_#{hns}_path(@resource)"), icon: 'fa-pencil-alt', title: t('commands.edit'), text: t('commands.edit'), data: {dismiss: 'modal', toggle: 'modal', target: '#new-update-dialog'}, html_class: 'btn-primary'})
/button btn mr-sm-2

app/views/groups/by_department.haml
// Table name singular, for url helpers
- helper_name_s = @resources.table_name.singularize
// Table name plural, for url helpers
- helper_name_p = @resources.table_name

- new_link = link_to_fa_button({url: new_group_path(department_id: params[:department_id]), text: t('commands.new'), html_class: 'btn-secondary', icon: 'fa-plus', data: {toggle: 'modal', target: '#new-update-dialog'}})
= render partial: 'layouts/admin_menu', locals: {title: t(@resources.table_name), index_url: by_department_url(params[:department_id]), new_link: new_link}

%p.text-center.alert.alert-secondary.mt-2.mb-1.h5
  =Catalogs::Department.find(params[:department_id]).name_es

#records
  = render partial: 'records', locals: {hnp: helper_name_p, hns: helper_name_s}
#show-dialog.modal{:role => "dialog", :tabindex => "-1"}
#new-update-dialog.modal{:role => "dialog", :tabindex => "-1"}
#delete-dialog.modal{:role => "dialog", :tabindex => "-1"}

-#%p.text-center= will_paginate @resources
%nav{"aria-label" => "..."}
  #paginate.pagination.justify-content-center.pagination-sm
    = will_paginate @resources, :container => false
%br

= javascript_pack_tag 'paginate', 'data-turbolinks-track': 'reload'

app/views/groups/delete.js.haml
$('#delete-dialog').html("#{escape_javascript(render(partial: 'layouts/delete', locals: {title: @resource.name_es, record: @resource } ))}");

app/views/groups/index.html.haml
// Table name singular, for url helpers
- helper_name_s = @resources.table_name.singularize
// Table name plural, for url helpers
- helper_name_p = @resources.table_name

- new_link = link_to_fa_button({url: eval("new_#{helper_name_s}_path"), text: t('commands.new'), html_class: 'btn-secondary', icon: 'fa-plus', data: {toggle: 'modal', target: '#new-update-dialog'}})
= render partial: 'layouts/admin_menu', locals: {title: t(@resources.table_name), index_url: eval("#{helper_name_p}_path"), new_link: new_link}

%br

#records
  = render partial: 'records', locals: {hnp: helper_name_p, hns: helper_name_s}
#show-dialog.modal{:role => "dialog", :tabindex => "-1"}
#new-update-dialog.modal{:role => "dialog", :tabindex => "-1"}
#delete-dialog.modal{:role => "dialog", :tabindex => "-1"}

-#%p.text-center= will_paginate @resources
%nav{"aria-label" => "..."}
  #paginate.pagination.justify-content-center.pagination-sm
    = will_paginate @resources, :container => false
%br

= javascript_pack_tag 'paginate', 'data-turbolinks-track': 'reload'


-#
  %h1 Listing groups

  %table
  %thead
    %tr
      %th Name es
      %th Name en
      %th Catalogs location
      %th
      %th
      %th

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.name_es
        %td= group.name_en
        %td= group.catalogs_location
        %td= link_to 'Show', group
        %td= link_to 'Edit', edit_group_path(group)
        %td= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }

  %br

  = link_to 'New Group', new_group_path